[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
# formatter = { command = "clang-format",  }

[language-server.clangd]
args = ["-header-insertion=never"]

[[language]]
name = "go"
indent = { tab-width = 4, unit = "    " }
