[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
# formatter = { command = "clang-format",  }

[language-server.clangd]
args = ["-header-insertion=never"]

[[language]]
name = "go"
indent = { tab-width = 4, unit = "    " }

[language-server.pylsp]
config = { pylsp.plugins.flake8.maxLineLength = 120, pylsp.plugins.pycodestyle.maxLineLength = 120  }

